// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyForeignCards.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyForeignCards.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260918100520_AddCategory")]
    partial class AddCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyForeignCards.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("MyForeignCards.Entities.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("translation");

                    b.HasKey("Id")
                        .HasName("pk_words");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_words_category_id");

                    b.ToTable("words", (string)null);
                });

            modelBuilder.Entity("MyForeignCards.Entities.Word", b =>
                {
                    b.HasOne("MyForeignCards.Entities.Category", "Categories")
                        .WithMany("Word")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_words_categories_category_id");

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("MyForeignCards.Entities.Category", b =>
                {
                    b.Navigation("Word");
                });
#pragma warning restore 612, 618
        }
    }
}
